[feat] add synchronize timestamp mode
orbbec/OrbbecSDK-K4A-Wrapper pull request #38
Opened 2024-02-01 03:30 UTC by zzuliys

2024-02-04 09:42 UTC, hzcyf requested changes

2024-02-04 09:42 UTC, hzcyf commented on include/k4a/k4atypes.h
> +} k4a_device_clock_sync_mode_t;
枚举类型命名和里边字段命名概念不同一

2024-02-04 09:42 UTC, hzcyf commented on include/k4a/k4a.h
> + * \param clock_sync_time
变量命名与变量含义不统一。 可以直接命名成param

2024-02-04 09:42 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +    if(current_device_clock_sync_mode == K4A_TIEMSTAMP_UNKNOWN){
什么条件下会等于K4A_TIEMSTAMP_UNKNOWN？ K4A_TIEMSTAMP_UNKNOWN这个定义是否有必要？

2024-02-04 09:42 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +    if(current_device_clock_sync_mode == K4A_TIEMSTAMP_UNKNOWN){
配置成K4A_TIEMSTAMP_RESET后这里就不需要清零么

2024-02-04 09:42 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +    ob_device_get_structured_data(device_ctx->device,
这个代码是不是应该放到if(current_device_clock_sync_mode == K4A_TIEMSTAMP_UNKNOWN) 内执行？

2024-02-04 09:42 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +                ob_enable_device_clock_sync(ob_context_handler->context, clock_sync_time, &ob_err);
同一个进程打开多个设备后，对其他中一个设备进行配置会不会影响到其他设备？

2024-02-04 09:42 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +                current_device_clock_sync_mode = K4A_TIMESTAMP_RESET;
current_device_clock_sync_mode 定义成全局变量的话，为什么需要传入device_handle，而不是直接用全局device list？

2024-02-04 09:44 UTC, hzcyf commented
将提交压缩一下，不要将反复修改的代码过程也提交了，不利于代码回溯

2024-02-07 07:12 UTC, zzuliys commented
> 将提交压缩一下，不要将反复修改的代码过程也提交了，不利于代码回溯

待代码通过审核后统一压缩提交记录

2024-02-07 07:15 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +            if(!(device_ctx->device)){
这个逻辑反了吧？

2024-02-07 07:25 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +                std::thread syncThread(device_timestamp_sync_with_host, *device_handle, param);
需要先把前一个线程退出

2024-02-07 07:25 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +                switch_device_clock_sync_mode(&device_handle, 0, K4A_DEVICE_CLOCK_SYNC_MODE_RESET);
close device 的时候为已经是reset模式还要切换一次reset模式？

2024-02-07 07:25 UTC, hzcyf commented on src/orbbec/ob_k4a_impl.cpp
> +    device_ctx->clock_sync_cv.notify_one();
只notify了，但没有保证线程一定已经退出。 线程不安全

2024-02-08 01:10 UTC, hzcyf approved these changes

2024-02-08 01:20 UTC, merged